version: '3.8'

services:
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8001

  turn:
    build:
      context: ./docker/turn
      dockerfile: Dockerfile
    ports:
      - "3478:3478/udp"
      - "3478:3478"
      - "5349:5349/udp"
      - "5349:5349"
    restart: always
    network_mode: host # Recommended for TURN servers to avoid port mapping overhead
