# Generated by Django 5.0.2 on 2026-02-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(default='text', max_length=20),
        ),
    ]
