# Generated by Django 5.0.2 on 2026-02-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
    ]
