# Generated by Django 5.0.2 on 2026-03-03 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_emailotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=10)),
                ('call_preference', models.CharField(choices=[('both', 'Both Audio & Video'), ('audio', 'Audio Only'), ('video', 'Video Only')], default='both', max_length=10)),
                ('app_lock_type', models.CharField(choices=[('none', 'None'), ('pin', 'PIN'), ('pattern', 'Pattern'), ('biometric', 'Biometric')], default='none', max_length=12)),
                ('app_lock_value', models.CharField(blank=True, max_length=255)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_follow_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_follow_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['to_user', 'status'], name='api_followr_to_user_51308f_idx')],
                'unique_together': {('from_user', 'to_user')},
            },
        ),
        migrations.CreateModel(
            name='LeagueStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_coins_earned', models.IntegerField(default=0)),
                ('total_call_seconds', models.IntegerField(default=0)),
                ('longest_call_seconds', models.IntegerField(default=0)),
                ('total_calls_received', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='league_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['-total_coins_earned'], name='api_leagues_total_c_c40ccb_idx'), models.Index(fields=['-total_call_seconds'], name='api_leagues_total_c_6c73ff_idx'), models.Index(fields=['-total_calls_received'], name='api_leagues_total_c_a612ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('follow_request', 'Follow Request'), ('follow_accepted', 'Follow Accepted'), ('story_like', 'Story Like'), ('story_comment', 'Story Comment'), ('story_post', 'New Story'), ('user_online', 'User Online'), ('live_start', 'Live Started'), ('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Accepted'), ('gift', 'Gift Received')], max_length=20)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='api_notific_recipie_28b188_idx'), models.Index(fields=['recipient', 'created_at'], name='api_notific_recipie_913487_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['story', 'created_at'], name='api_storyco_story_i_96ea79_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['story'], name='api_storyli_story_i_76cbbc_idx')],
                'unique_together': {('story', 'user')},
            },
        ),
    ]
