# Generated by Django 5.0.2 on 2026-03-03 12:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_usersetting_followrequest_leaguestats_notification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('coins_staked', models.IntegerField(default=0)),
                ('winner_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('result_coins', models.IntegerField(default=0)),
                ('result_money', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonetizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('audio_call', 'Audio Call'), ('video_call', 'Video Call'), ('live', 'Live Stream'), ('chat', 'Chat Message'), ('photo', 'Photo Message'), ('video_msg', 'Video Message'), ('bet_match', 'Bet Match'), ('gift', 'Gift Send')], max_length=20, unique=True)),
                ('cost_per_minute', models.IntegerField(default=0)),
                ('cost_per_message', models.IntegerField(default=0)),
                ('cost_per_media', models.IntegerField(default=0)),
                ('night_cost_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('reward_male', models.IntegerField(default=0)),
                ('reward_female', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='leaguestats',
            name='bet_match_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaguestats',
            name='total_money_earned',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='leaguestats',
            name='total_time_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='caption',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='money_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='story',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='leaguestats',
            index=models.Index(fields=['-total_money_earned'], name='api_leagues_total_m_2b748e_idx'),
        ),
        migrations.AddIndex(
            model_name='leaguestats',
            index=models.Index(fields=['-bet_match_wins'], name='api_leagues_bet_mat_e2f0c3_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['user', 'expires_at'], name='api_story_user_id_036fae_idx'),
        ),
        migrations.AddField(
            model_name='betmatch',
            name='female_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bet_matches_as_female', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='betmatch',
            name='male_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_matches_as_male', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='monetizationrule',
            index=models.Index(fields=['action_type', 'is_active'], name='api_monetiz_action__2df966_idx'),
        ),
        migrations.AddIndex(
            model_name='betmatch',
            index=models.Index(fields=['status'], name='api_betmatc_status_ac8b00_idx'),
        ),
        migrations.AddIndex(
            model_name='betmatch',
            index=models.Index(fields=['male_user'], name='api_betmatc_male_us_d689d6_idx'),
        ),
        migrations.AddIndex(
            model_name='betmatch',
            index=models.Index(fields=['female_user'], name='api_betmatc_female__dca066_idx'),
        ),
    ]
