# Generated by Django 5.0.2 on 2026-03-06 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_posts_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Removed StoryComment and StoryLike field deletions to fix DB sync
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='betmatch',
            name='api_betmatc_status_ac8b00_idx',
        ),
        migrations.RemoveIndex(
            model_name='betmatch',
            name='api_betmatc_male_us_d689d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='betmatch',
            name='api_betmatc_female__dca066_idx',
        ),
        migrations.RemoveIndex(
            model_name='followrequest',
            name='api_followr_to_user_51308f_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaguestats',
            name='api_leagues_total_c_c40ccb_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaguestats',
            name='api_leagues_total_c_6c73ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaguestats',
            name='api_leagues_total_c_a612ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaguestats',
            name='api_leagues_total_m_2b748e_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaguestats',
            name='api_leagues_bet_mat_e2f0c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='monetizationrule',
            name='api_monetiz_action__2df966_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='api_notific_recipie_28b188_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='api_notific_recipie_913487_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='api_post_created_a6c29a_idx',
        ),
        migrations.RemoveIndex(
            model_name='postlike',
            name='api_postlik_post_id_bb497a_idx',
        ),
        migrations.RemoveIndex(
            model_name='pushtoken',
            name='api_pushtok_user_id_abeb69_idx',
        ),
        migrations.RemoveIndex(
            model_name='story',
            name='api_story_user_id_036fae_idx',
        ),
        migrations.AlterUniqueTogether(
            name='pushtoken',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='betmatch',
            name='coins_staked',
        ),
        migrations.RemoveField(
            model_name='followrequest',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='leaguestats',
            name='total_time_seconds',
        ),
        migrations.RemoveField(
            model_name='monetizationrule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='story',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='story',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='story',
            name='media_url',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='betmatch',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='betmatch',
            name='winner_gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='monetizationrule',
            name='action_type',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pushtoken',
            name='expo_token',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='app_lock_type',
            field=models.CharField(choices=[('none', 'None'), ('pin', 'PIN'), ('pattern', 'Pattern')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='call_preference',
            field=models.CharField(default='both', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='theme',
            field=models.CharField(default='system', max_length=20),
        ),
        # Removed DeleteModel for StoryComment and StoryLike
        migrations.RemoveField(
            model_name='pushtoken',
            name='device',
        ),
    ]
