# Generated by Django 5.0.2 on 2026-03-07 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_storylike_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='storylike',
        #     unique_together=None,
        # ),
        # migrations.RemoveField(
        #     model_name='storylike',
        #     name='story',
        # ),
        # migrations.RemoveField(
        #     model_name='storylike',
        #     name='user',
        # ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        # migrations.DeleteModel(
        #     name='StoryComment',
        # ),
        # migrations.DeleteModel(
        #     name='StoryLike',
        # ),
    ]
