# Generated by Django 5.0.2 on 2026-03-07 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_storylike_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReelComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReelLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        # migrations.RemoveIndex(
        #     model_name='storycomment',
        #     name='api_storyco_story_i_96ea79_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='storylike',
        #     name='api_storyli_story_i_76cbbc_idx',
        # ),
        migrations.AddField(
            model_name='pushtoken',
            name='device',
            field=models.CharField(blank=True, max_length=50),
        ),
        # migrations.AlterField(
        #     model_name='storycomment',
        #     name='text',
        #     field=models.TextField(),
        # ),
        migrations.AddField(
            model_name='reelcomment',
            name='reel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.reel'),
        ),
        migrations.AddField(
            model_name='reelcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reellike',
            name='reel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.reel'),
        ),
        migrations.AddField(
            model_name='reellike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='reellike',
            unique_together={('reel', 'user')},
        ),
    ]
