# Generated by Django 5.0.2 on 2026-03-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_reelcomment_reellike_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='storycomment',
            name='api_storyco_story_i_96ea79_idx',
        ),
        migrations.RemoveIndex(
            model_name='storylike',
            name='api_storyli_story_i_76cbbc_idx',
        ),
        migrations.AlterField(
            model_name='storycomment',
            name='text',
            field=models.TextField(),
        ),
    ]
