# Generated by Django 5.0.2 on 2026-03-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_storycomment_api_storyco_story_i_96ea79_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
