# Generated by Django 5.0.2 on 2026-03-18 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_questionbank_interactivegamesession_gameeventlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='safety_level',
            field=models.CharField(default='safe', max_length=20),
        ),
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('room_type', models.CharField(choices=[('couple', 'Couple'), ('group', 'Group'), ('random', 'Random')], default='group', max_length=20)),
                ('status', models.CharField(default='lobby', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='interactivegamesession',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='api.gameroom'),
        ),
    ]
