# Generated by Django 5.0.2 on 2026-03-18 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_matchmakingqueue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interactivegamesession',
            name='current_questioner_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interactivegamesession',
            name='selected_option',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='interactivegamesession',
            name='timer_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
