# Generated by Django 5.0.2 on 2026-03-19 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_interactivegamesession_current_questioner_player_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='reel',
            name='visibility',
            field=models.CharField(default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='story',
            name='visibility',
            field=models.CharField(default='all', max_length=20),
        ),
        migrations.CreateModel(
            name='StreakUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.FileField(blank=True, null=True, upload_to='streaks/')),
                ('media_type', models.CharField(default='image', max_length=10)),
                ('visibility', models.CharField(default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CloseFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('close_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_friended_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_friends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'close_friend')},
            },
        ),
    ]
