# Generated by Django 5.0.2 on 2026-03-21 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_post_is_archived_reel_is_archived_room_is_archived_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='last_uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streaks_last_uploader', to=settings.AUTH_USER_MODEL),
        ),
    ]
