# Generated by Django 5.0.2 on 2026-03-22 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_streak_last_uploader'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreakLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('streak_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.streakupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('streak_upload', 'user')},
            },
        ),
        migrations.CreateModel(
            name='StreakReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('fire', 'Fire')], default='fire', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('streak_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='api.streakupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('streak_upload', 'user', 'reaction_type')},
            },
        ),
    ]
