# Generated by Django 5.0.2 on 2026-03-22 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_streaklike_streakreaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='streakreaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='streakreaction',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='streakreaction',
            name='streak_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='api.streakupload'),
        ),
        migrations.AlterUniqueTogether(
            name='streakreaction',
            unique_together={('streak_upload', 'user', 'recipient', 'reaction_type')},
        ),
    ]
