# Generated by Django 5.0.2 on 2026-03-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_streakreaction_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='caption',
            field=models.TextField(blank=True),
        ),
    ]
