# Generated by Django 5.0.2 on 2026-03-24 03:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_story_caption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reel',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_reels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_stories', to=settings.AUTH_USER_MODEL),
        ),
    ]
