# Generated by Django 5.0.2 on 2026-03-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_post_mentions_reel_mentions_story_mentions'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='room_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
