# Generated by Django 5.0.2 on 2026-03-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_callsession_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='biometrics_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='face_unlock_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
