# Generated by Django 5.0.2 on 2026-03-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_usersetting_biometrics_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='face_registration_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='fingerprint_registration_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
