# Generated by Django 5.0.2 on 2026-04-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_db_charset'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='receive_offline_calls',
            field=models.BooleanField(default=True),
        ),
    ]
