# Generated by Django 5.0.2 on 2026-04-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_usersetting_receive_offline_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='chat_theme',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
