# Generated by Django 5.0.2 on 2026-04-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_message_seen_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushtoken',
            name='expo_token',
            field=models.CharField(max_length=255),
        ),
    ]
