# Generated by Django 5.0.2 on 2026-04-04 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_pushtoken_expo_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interactivegamesession',
            name='turn_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='matchmakingqueue',
            name='game_type',
            field=models.CharField(default='all', max_length=50),
        ),
        migrations.CreateModel(
            name='MatchmakingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('is_expanded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closeness_score', models.IntegerField(default=0)),
                ('streak_count', models.IntegerField(default=0)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('user_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_initiated', to=settings.AUTH_USER_MODEL)),
                ('user_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_accepted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_one', 'user_two')},
            },
        ),
    ]
