# Generated by Django 5.0.2 on 2026-04-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_interactivegamesession_turn_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='game_mode',
            field=models.CharField(choices=[('truth_dare', 'Truth or Dare'), ('romantic', 'Romantic Connection'), ('deep', 'Deep Questions'), ('flirty', 'Flirty Challenge'), ('roleplay', 'Roleplay Lite'), ('memory', 'Memory Meter'), ('draw_guess', 'Draw & Guess'), ('coop', 'Co-op Task'), ('random_match', 'Random Match')], default='truth_dare', max_length=20),
        ),
    ]
