# Generated by Django 5.0.2 on 2026-04-04 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_gameroom_game_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='streakupload',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='streakupload',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_streaks', to=settings.AUTH_USER_MODEL),
        ),
    ]
