# Generated by Django 5.0.2 on 2026-04-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_streakupload_caption_streakupload_mentions'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguestats',
            name='last_reset_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaguestats',
            name='monthly_audio_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaguestats',
            name='monthly_video_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaguestats',
            name='total_audio_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaguestats',
            name='total_video_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
