# Generated by Django 5.0.2 on 2026-04-06 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_cointransaction_target_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_post_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_post_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.postcomment'),
        ),
        migrations.AddField(
            model_name='reelcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_reel_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reelcomment',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_reel_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reelcomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.reelcomment'),
        ),
        migrations.AddField(
            model_name='storycomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_story_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storycomment',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_story_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storycomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.storycomment'),
        ),
        migrations.AddField(
            model_name='streakcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_streak_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='streakcomment',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_streak_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='streakcomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.streakcomment'),
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Original Audio', max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('file_url', models.FileField(upload_to='audios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_audios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='api.audio'),
        ),
        migrations.AddField(
            model_name='reel',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reels', to='api.audio'),
        ),
    ]
