# Generated by Django 5.0.2 on 2026-04-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_postcomment_likes_postcomment_mentions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
