# Generated by Django 5.0.2 on 2026-04-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_hashtags_notes_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='duration_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audio',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audio',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='audio',
            name='shazam_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
