# Generated by Django 5.0.2 on 2026-04-08 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_audio_duration_ms_audio_is_trending_audio_language_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='category',
            field=models.CharField(default='Trending', max_length=50),
        ),
        migrations.AddField(
            model_name='audio',
            name='external_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='is_cached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='api.audio'),
        ),
        migrations.AddField(
            model_name='streakupload',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streak_uploads', to='api.audio'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Saved Items', max_length=120)),
                ('type', models.CharField(choices=[('post', 'Posts'), ('reel', 'Reels'), ('audio', 'Audio'), ('general', 'General')], default='general', max_length=20)),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Highlight', max_length=50)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='highlights/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.audio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_audios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'audio')},
            },
        ),
        migrations.CreateModel(
            name='HighlightStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='api.highlight')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.story')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('highlight', 'story')},
            },
        ),
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.audio')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.collection')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.post')),
                ('reel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.reel')),
            ],
            options={
                'unique_together': {('collection', 'post', 'reel', 'audio')},
            },
        ),
    ]
