# Generated by Django 5.0.2 on 2026-04-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_audio_category_audio_external_id_audio_is_cached_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='reels/thumbnails/'),
        ),
    ]
