# Generated by Django 5.0.2 on 2026-04-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_note_mentions_notelike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/covers/'),
        ),
        migrations.AddField(
            model_name='reel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='reels/covers/'),
        ),
    ]
