# Generated by Django 5.0.2 on 2026-04-12 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_post_cover_image_reel_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='callsession',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='active_calls_participated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='callee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
