# Generated by Django 5.0.2 on 2026-04-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_callsession_is_group_callsession_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio_start_sec',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reel',
            name='audio_start_sec',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='audio_start_sec',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='streakupload',
            name='audio_start_sec',
            field=models.IntegerField(default=0),
        ),
    ]
