# Generated by Django 5.0.2 on 2026-04-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_post_audio_start_sec_reel_audio_start_sec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='file_url',
            field=models.FileField(max_length=1000, upload_to='audios/'),
        ),
    ]
