# Generated by Django 6.0.4 on 2026-04-16 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_alter_audio_file_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='editor_metadata_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='post',
            name='editor_metadata_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reel',
            name='editor_metadata_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='story',
            name='editor_metadata_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='streakupload',
            name='editor_metadata_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='EditorDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('story', 'Story'), ('streak', 'Streak'), ('reel', 'Reel'), ('note', 'Note')], max_length=20)),
                ('caption', models.TextField(blank=True)),
                ('note_text', models.CharField(blank=True, max_length=60)),
                ('editor_metadata_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_drafts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FilterSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(max_length=50)),
                ('intensity', models.FloatField(default=1.0)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filter', to='api.editordraft')),
            ],
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=50)),
                ('media_kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('thumbnail', 'Thumbnail')], max_length=20)),
                ('original_url', models.FileField(upload_to='assets/original/')),
                ('processed_url', models.FileField(blank=True, null=True, upload_to='assets/processed/')),
                ('thumbnail_url', models.ImageField(blank=True, null=True, upload_to='assets/thumbnails/')),
                ('mime_type', models.CharField(max_length=100)),
                ('duration', models.FloatField(default=0)),
                ('file_size', models.BigIntegerField(default=0)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='ready', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='editordraft',
            name='media_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mediaasset'),
        ),
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(default='jiosaavn', max_length=50)),
                ('provider_track_id', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('album_name', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.IntegerField()),
                ('audio_url', models.FileField(blank=True, null=True, upload_to='music/full/')),
                ('preview_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('cover_image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('raw_provider_payload_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('provider_name', 'provider_track_id')},
            },
        ),
        migrations.CreateModel(
            name='MusicClipSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(default='jiosaavn', max_length=50)),
                ('provider_track_id', models.CharField(max_length=255)),
                ('clip_start_seconds', models.FloatField(default=0)),
                ('clip_end_seconds', models.FloatField(default=0)),
                ('clip_duration', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music_selection', to='api.editordraft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.musictrack')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='music_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_usages_legacy', to='api.musictrack'),
        ),
        migrations.AddField(
            model_name='post',
            name='music_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_usages', to='api.musictrack'),
        ),
        migrations.AddField(
            model_name='reel',
            name='music_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_usages', to='api.musictrack'),
        ),
        migrations.AddField(
            model_name='story',
            name='music_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_usages', to='api.musictrack'),
        ),
        migrations.AddField(
            model_name='streakupload',
            name='music_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_usages', to='api.musictrack'),
        ),
        migrations.CreateModel(
            name='OverlayItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overlay_type', models.CharField(choices=[('text', 'Text'), ('emoji', 'Emoji'), ('sticker', 'Sticker')], max_length=20)),
                ('content', models.TextField()),
                ('pos_x', models.FloatField()),
                ('pos_y', models.FloatField()),
                ('scale_value', models.FloatField(default=1.0)),
                ('rotation_value', models.FloatField(default=0.0)),
                ('opacity', models.FloatField(default=1.0)),
                ('z_index', models.IntegerField(default=0)),
                ('start_time', models.FloatField(default=0)),
                ('end_time', models.FloatField(blank=True, null=True)),
                ('color_code', models.CharField(blank=True, max_length=20, null=True)),
                ('background_color', models.CharField(blank=True, max_length=20, null=True)),
                ('font_family', models.CharField(blank=True, max_length=50, null=True)),
                ('font_size', models.IntegerField(default=32)),
                ('animation_type', models.CharField(blank=True, max_length=50, null=True)),
                ('animation_config_json', models.JSONField(blank=True, default=dict)),
                ('extra_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlays', to='api.editordraft')),
            ],
        ),
        migrations.CreateModel(
            name='PublishedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=20)),
                ('processed_media_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('caption', models.TextField(blank=True)),
                ('note_text', models.CharField(blank=True, max_length=60)),
                ('editor_metadata_json', models.JSONField(blank=True, default=dict)),
                ('publish_status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('published', 'Published'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='published', max_length=20)),
                ('visibility', models.CharField(default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.mediaasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_contents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PublishedMusicAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(default='jiosaavn', max_length=50)),
                ('provider_track_id', models.CharField(max_length=255)),
                ('clip_start_seconds', models.FloatField(default=0)),
                ('clip_end_seconds', models.FloatField(default=0)),
                ('clip_duration', models.FloatField(default=0)),
                ('original_audio_volume', models.FloatField(default=1.0)),
                ('music_volume', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='music', to='api.publishedcontent')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.musictrack')),
            ],
        ),
        migrations.CreateModel(
            name='UserMusicFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.musictrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'track')},
            },
        ),
    ]
