# Generated by Django 5.0.2 on 2026-04-17 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_note_editor_metadata_json_post_editor_metadata_json_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='note',
            name='audio_start_sec',
        ),
        migrations.RemoveField(
            model_name='note',
            name='editor_metadata_json',
        ),
        migrations.RemoveField(
            model_name='note',
            name='mentions',
        ),
        migrations.RemoveField(
            model_name='note',
            name='music_track',
        ),
        migrations.AddField(
            model_name='note',
            name='emoji',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='note',
            name='music_artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='music_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='music_thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='music_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('text', 'Text'), ('music', 'Music')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
