# Generated by Django 5.0.2 on 2026-04-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_remove_note_audio_remove_note_audio_start_sec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='music_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
