# Generated by Django 5.0.2 on 2026-04-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_note_lyrics_note_music_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='music_image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
