# Generated by Django 5.0.2 on 2026-04-19 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_note_music_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='original', max_length=50)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('is_synced', models.BooleanField(default=False)),
                ('raw_lrc_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lyrics_v2', to='api.musictrack')),
            ],
        ),
        migrations.CreateModel(
            name='LyricBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_ms', models.IntegerField()),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.musictrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyric_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp_ms'],
            },
        ),
        migrations.CreateModel(
            name='LyricLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('start_time_ms', models.IntegerField()),
                ('end_time_ms', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('translated_text', models.TextField(blank=True, null=True)),
                ('romanized_text', models.TextField(blank=True, null=True)),
                ('lyric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api.lyric')),
            ],
            options={
                'ordering': ['start_time_ms', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserFavoriteLyric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lyric_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.lyricline')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_lyrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lyric_line')},
            },
        ),
    ]
