# Generated by Django 5.0.2 on 2026-04-19 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_lyric_lyricbookmark_lyricline_userfavoritelyric'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='background_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='note',
            name='clip_end_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='clip_start_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='font_style',
            field=models.CharField(default='classic', max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='mood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='sticker_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='NoteComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_note_comments', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.note')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.notecomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
