# Generated by Django 5.0.2 on 2026-04-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_note_background_config_note_clip_end_ms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(default='User', max_length=120),
        ),
    ]
