# Generated by Django 5.0.2 on 2026-08-18 04:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_alter_profile_display_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.PositiveBigIntegerField(db_index=True, help_text='ID of the Reel or Post this embedding refers to.', unique=True)),
                ('content_type', models.CharField(choices=[('reel', 'Reel'), ('post', 'Post')], default='reel', max_length=10)),
                ('embedding_blob', models.BinaryField(help_text='Numpy float32 array bytes')),
                ('model_version', models.CharField(default='all-MiniLM-L6-v2', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='engagement_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='post',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='engagement_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='reel',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reel',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='audio',
            name='file_url',
            field=models.FileField(max_length=1000, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.CreateModel(
            name='ContentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.PositiveBigIntegerField(db_index=True, help_text='ID of the Reel or Post this score refers to.', unique=True)),
                ('content_type', models.CharField(choices=[('reel', 'Reel'), ('post', 'Post')], default='reel', help_text='Type of content for disambiguation.', max_length=10)),
                ('popularity_score', models.FloatField(default=0.0)),
                ('cf_score', models.FloatField(default=0.0)),
                ('combined_score', models.FloatField(db_index=True, default=0.0, help_text='Weighted blend: 0.6 * popularity + 0.4 * cf. Pre-computed.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-combined_score'],
                'indexes': [models.Index(fields=['-combined_score'], name='idx_cscore_combined_desc')],
            },
        ),
        migrations.CreateModel(
            name='UserInterestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_term', models.JSONField(blank=True, default=dict)),
                ('short_term', models.JSONField(blank=True, default=dict)),
                ('session', models.JSONField(blank=True, default=dict)),
                ('negative_confidence', models.JSONField(blank=True, default=dict)),
                ('last_session_id', models.UUIDField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interest_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_id', models.PositiveBigIntegerField(db_index=True, help_text='ID of the Reel/Post/Content this event refers to.')),
                ('creator_id', models.PositiveBigIntegerField(blank=True, help_text='ID of the content creator (denormalized for fast queries).', null=True)),
                ('event_type', models.CharField(choices=[('watch', 'Watch'), ('replay', 'Replay'), ('like', 'Like'), ('save', 'Save'), ('share', 'Share'), ('comment', 'Comment'), ('follow', 'Follow'), ('skip', 'Skip'), ('not_interested', 'Not Interested'), ('hide', 'Hide'), ('report', 'Report')], max_length=20)),
                ('watch_pct', models.FloatField(default=0.0, help_text='Fraction of content watched (0.0 to 1.0). Only meaningful for watch/replay events.')),
                ('session_id', models.UUIDField(blank=True, db_index=True, help_text='Client-assigned session ID. Used for session-interest vector.', null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('source', models.CharField(choices=[('feed', 'Feed'), ('search', 'Search'), ('profile', 'Profile'), ('explore', 'Explore')], default='feed', max_length=20)),
                ('device_context', models.JSONField(blank=True, default=dict, help_text='Flexible client metadata: time_of_day, platform, etc.')),
                ('is_flagged', models.BooleanField(db_index=True, default=False, help_text='True if this event was flagged by the anti-abuse pre-filter.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'content_id', 'timestamp'], name='idx_recevent_user_content_ts'), models.Index(fields=['user', 'timestamp'], name='idx_recevent_user_ts'), models.Index(fields=['content_id', 'timestamp'], name='idx_recevent_content_ts')],
            },
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('session_id', models.UUIDField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_events', models.IntegerField(default=0)),
                ('avg_watch_pct', models.FloatField(default=0.0)),
                ('skip_rate', models.FloatField(default=0.0)),
                ('not_interested_count', models.IntegerField(default=0)),
                ('satisfaction_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['user', '-start_time'], name='api_session_user_id_712f5b_idx')],
            },
        ),
    ]
