# Generated by Django 5.0.2 on 2026-08-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_contentembedding_post_engagement_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='engagement_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='post',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recevent',
            name='milestones',
            field=models.JSONField(blank=True, default=list, help_text='Array of granular milestones crossed, e.g. ["play_start", "2s", "25%", "50%"].'),
        ),
        migrations.AddField(
            model_name='reel',
            name='engagement_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='reel',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reel',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recevent',
            name='event_type',
            field=models.CharField(choices=[('watch', 'Watch'), ('replay', 'Replay'), ('like', 'Like'), ('save', 'Save'), ('share', 'Share'), ('comment', 'Comment'), ('follow', 'Follow'), ('skip', 'Skip'), ('not_interested', 'Not Interested'), ('hide', 'Hide'), ('report', 'Report'), ('revisit', 'Revisit'), ('rewatch', 'Rewatch'), ('rewatch_complete', 'Rewatch Complete'), ('navigation_back', 'Navigation Back')], max_length=20),
        ),
    ]
