# Generated by Django 5.0.2 on 2026-08-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_post_engagement_score_post_share_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_id', models.PositiveBigIntegerField(db_index=True, unique=True)),
                ('avg_completion_rate', models.FloatField(default=0.0)),
                ('share_rate', models.FloatField(default=0.0)),
                ('save_rate', models.FloatField(default=0.0)),
                ('report_rate', models.FloatField(default=0.0)),
                ('upload_count_30d', models.IntegerField(default=0)),
                ('quality_score', models.FloatField(db_index=True, default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
