# Generated by Django 5.0.2 on 2026-08-21 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_creatorscore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterestEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('CATEGORY', 'Category'), ('CREATOR', 'Creator'), ('BRAND', 'Brand'), ('TAG', 'Tag')], db_index=True, max_length=20)),
                ('entity_id', models.CharField(db_index=True, max_length=100)),
                ('interest_score', models.FloatField(db_index=True, default=0.0)),
                ('positive_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('last_interacted_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_entities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'entity_type', '-interest_score'], name='api_userint_user_id_0c6c02_idx'), models.Index(fields=['entity_type', 'entity_id', '-interest_score'], name='api_userint_entity__f6420c_idx')],
                'unique_together': {('user', 'entity_type', 'entity_id')},
            },
        ),
    ]
