# Generated by Django 5.0.2 on 2026-08-21 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_userinterestentity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='recevent',
            name='idx_recevent_user_content_ts',
        ),
        migrations.RemoveIndex(
            model_name='recevent',
            name='idx_recevent_content_ts',
        ),
        migrations.AddField(
            model_name='recevent',
            name='content_type',
            field=models.CharField(choices=[('reel', 'Reel'), ('post', 'Post')], db_index=True, default='reel', help_text='The type of content (reel or post).', max_length=10),
        ),
        migrations.AlterField(
            model_name='contentscore',
            name='content_id',
            field=models.PositiveBigIntegerField(db_index=True, help_text='ID of the Reel or Post this score refers to.'),
        ),
        migrations.AlterUniqueTogether(
            name='contentscore',
            unique_together={('content_type', 'content_id')},
        ),
        migrations.AddIndex(
            model_name='recevent',
            index=models.Index(fields=['user', 'content_type', 'content_id', 'timestamp'], name='idx_recev_user_ctype_cid_ts'),
        ),
        migrations.AddIndex(
            model_name='recevent',
            index=models.Index(fields=['content_type', 'content_id', 'timestamp'], name='idx_recev_ctype_cid_ts'),
        ),
    ]
