# Generated by Django 5.0.2 on 2026-08-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_remove_recevent_idx_recevent_user_content_ts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentembedding',
            name='content_id',
            field=models.PositiveBigIntegerField(db_index=True, help_text='ID of the Reel or Post this embedding refers to.'),
        ),
        migrations.AlterUniqueTogether(
            name='contentembedding',
            unique_together={('content_type', 'content_id')},
        ),
    ]
