# Generated by Django 5.0.2 on 2026-08-21 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_alter_contentembedding_content_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreatorAffinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affinity_score', models.FloatField(db_index=True, default=0.0)),
                ('interaction_count', models.IntegerField(default=0)),
                ('last_interaction_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_affinities_target', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_affinities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-affinity_score'], name='api_usercre_user_id_4b4b17_idx')],
                'unique_together': {('user', 'creator')},
            },
        ),
        migrations.CreateModel(
            name='UserSocialAffinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affinity_score', models.FloatField(db_index=True, default=0.0)),
                ('interaction_count', models.IntegerField(default=0)),
                ('last_interaction_at', models.DateTimeField(auto_now=True)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_affinities_target', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_affinities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-affinity_score'], name='api_usersoc_user_id_e3586f_idx')],
                'unique_together': {('user', 'target_user')},
            },
        ),
    ]
