# Generated by Django 5.0.2 on 2026-08-21 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_usercreatoraffinity_usersocialaffinity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recevent',
            name='loop_index',
            field=models.PositiveSmallIntegerField(default=0, help_text='Increments per in-session Loop/Replay.'),
        ),
        migrations.AddField(
            model_name='recevent',
            name='play_session_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='One per continuous engagement with a single reel.', null=True),
        ),
        migrations.AddField(
            model_name='recevent',
            name='scroll_direction',
            field=models.CharField(blank=True, help_text='Direction scrolled (up or down).', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='recevent',
            name='watch_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Total time spent watching during this event.', null=True),
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='is_reengagement_session',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='total_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='total_reels_skipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='total_reels_watched',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='total_shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='total_watch_time_sec',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recevent',
            name='content_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, help_text='ID of the Reel/Post/Content this event refers to.', null=True),
        ),
        migrations.AlterField(
            model_name='recevent',
            name='content_type',
            field=models.CharField(choices=[('reel', 'Reel'), ('post', 'Post'), ('profile', 'Profile'), ('search_query', 'Search Query')], db_index=True, default='reel', help_text='The type of content (reel, post, profile, search).', max_length=20),
        ),
        migrations.AlterField(
            model_name='recevent',
            name='event_type',
            field=models.CharField(choices=[('watch', 'Watch'), ('replay', 'Replay'), ('like', 'Like'), ('save', 'Save'), ('share', 'Share'), ('comment', 'Comment'), ('follow', 'Follow'), ('skip', 'Skip'), ('not_interested', 'Not Interested'), ('hide', 'Hide'), ('report', 'Report'), ('revisit', 'Revisit'), ('rewatch', 'Rewatch'), ('rewatch_complete', 'Rewatch Complete'), ('navigation_back', 'Navigation Back'), ('impression_start', 'Impression Start'), ('progress', 'Progress'), ('loop', 'Loop'), ('impression_end', 'Impression End'), ('profile_view', 'Profile View'), ('search', 'Search'), ('message', 'Message'), ('tag', 'Tag'), ('mention', 'Mention')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recevent',
            name='session_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Overall app session ID (legacy).', null=True),
        ),
        migrations.CreateModel(
            name='UserContentInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.PositiveBigIntegerField(db_index=True)),
                ('content_type', models.CharField(default='reel', max_length=20)),
                ('status', models.CharField(choices=[('skipped', 'Skipped'), ('watched', 'Watched'), ('rewatched', 'Rewatched')], max_length=16)),
                ('best_watch_percent', models.FloatField(default=0.0)),
                ('total_watch_ms', models.PositiveIntegerField(default=0)),
                ('session_count', models.PositiveSmallIntegerField(default=0)),
                ('replay_count', models.PositiveSmallIntegerField(default=0)),
                ('skip_count', models.PositiveSmallIntegerField(default=0)),
                ('first_watched_at', models.DateTimeField(blank=True, null=True)),
                ('last_interacted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'content_type', 'status'], name='api_usercon_user_id_18078e_idx'), models.Index(fields=['user', 'last_interacted_at'], name='api_usercon_user_id_afac00_idx')],
                'unique_together': {('user', 'content_id', 'content_type')},
            },
        ),
    ]
