# Generated by Django 5.0.2 on 2026-08-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_recevent_loop_index_recevent_play_session_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(db_index=True)),
                ('content_id', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(default='reel', max_length=10)),
                ('candidate_source', models.CharField(help_text='e.g. SOCIAL_GRAPH, TRENDING, EXPLORE', max_length=50)),
                ('source_user_id', models.PositiveBigIntegerField(blank=True, help_text='If recommended because of a friend', null=True)),
                ('recommendation_score', models.FloatField(default=0.0)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('position', models.IntegerField(default=0)),
                ('shown_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'content_id'], name='api_recomme_user_id_552617_idx'), models.Index(fields=['session_id'], name='api_recomme_session_798c0a_idx')],
            },
        ),
    ]
