# Generated by Django 5.0.2 on 2026-08-21 13:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_recommendationimpression'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReelViewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_id', models.PositiveBigIntegerField(db_index=True)),
                ('content_type', models.CharField(db_index=True, default='reel', max_length=20)),
                ('play_session_id', models.UUIDField(help_text='Links to raw RecEvents for this viewing session', unique=True)),
                ('feed_session_id', models.UUIDField(blank=True, db_index=True, help_text='Links multiple views in one continuous feed scroll', null=True)),
                ('max_watch_percent', models.FloatField(default=0.0)),
                ('total_watch_ms', models.PositiveIntegerField(default=0)),
                ('loop_count', models.PositiveSmallIntegerField(default=0)),
                ('session_outcome', models.CharField(choices=[('QUICK_SKIP', 'Quick Skip (<15%)'), ('PARTIAL_SKIP', 'Partial Skip (15-70%)'), ('NORMAL_EXIT', 'Normal Exit (70-99%)'), ('COMPLETED', 'Completed (>=99%)'), ('REWATCH_EXIT', 'Rewatch Exit')], max_length=20)),
                ('is_meaningful_view', models.BooleanField(db_index=True, default=False)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='usercontentinterest',
            name='api_usercon_user_id_18078e_idx',
        ),
        migrations.RemoveIndex(
            model_name='usercontentinterest',
            name='api_usercon_user_id_afac00_idx',
        ),
        migrations.RemoveField(
            model_name='usercontentinterest',
            name='best_watch_percent',
        ),
        migrations.RemoveField(
            model_name='usercontentinterest',
            name='first_watched_at',
        ),
        migrations.RemoveField(
            model_name='usercontentinterest',
            name='last_interacted_at',
        ),
        migrations.RemoveField(
            model_name='usercontentinterest',
            name='replay_count',
        ),
        migrations.RemoveField(
            model_name='usercontentinterest',
            name='session_count',
        ),
        migrations.RemoveField(
            model_name='usercontentinterest',
            name='skip_count',
        ),
        migrations.RemoveField(
            model_name='usercontentinterest',
            name='status',
        ),
        migrations.AddField(
            model_name='recevent',
            name='feed_session_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Links multiple views in one continuous feed scroll.', null=True),
        ),
        migrations.AddField(
            model_name='usercontentinterest',
            name='completed_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercontentinterest',
            name='first_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercontentinterest',
            name='impression_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercontentinterest',
            name='last_action',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usercontentinterest',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercontentinterest',
            name='last_watch_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='usercontentinterest',
            name='max_watch_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='usercontentinterest',
            name='meaningful_view_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercontentinterest',
            name='partial_skip_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercontentinterest',
            name='quick_skip_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercontentinterest',
            name='rewatch_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercontentinterest',
            name='view_session_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='usercontentinterest',
            index=models.Index(fields=['user', 'content_type', 'last_action'], name='api_usercon_user_id_fe27c2_idx'),
        ),
        migrations.AddIndex(
            model_name='usercontentinterest',
            index=models.Index(fields=['user', 'last_seen_at'], name='api_usercon_user_id_fdcf44_idx'),
        ),
        migrations.AddField(
            model_name='reelviewsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_view_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reelviewsession',
            index=models.Index(fields=['user', 'content_type', 'content_id'], name='api_reelvie_user_id_428d6b_idx'),
        ),
        migrations.AddIndex(
            model_name='reelviewsession',
            index=models.Index(fields=['feed_session_id', 'started_at'], name='api_reelvie_feed_se_604967_idx'),
        ),
    ]
