# Generated by Django 5.0.2 on 2026-08-22 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_reelviewsession_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocialaffinity',
            name='comment_score',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='usersocialaffinity',
            name='content_score',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='usersocialaffinity',
            name='follow_score',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='usersocialaffinity',
            name='message_score',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='usersocialaffinity',
            name='profile_score',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='usersocialaffinity',
            name='tag_score',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='usersocialaffinity',
            name='affinity_score',
            field=models.DecimalField(db_index=True, decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='usersocialaffinity',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_by_affinities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProfileViewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(help_text='e.g. REEL, POST, SEARCH, FLOATING_PROFILE', max_length=40)),
                ('source_content_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('source_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_received', to=settings.AUTH_USER_MODEL)),
                ('viewer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['viewer_user', 'profile_user', 'created_at'], name='api_profile_viewer__ed58ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialDiscoveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(help_text='e.g. REEL_LIKER, COMMENTER, FLOATING_PROFILE', max_length=40)),
                ('source_content_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('surface', models.CharField(help_text='e.g. FLOATING_PROFILE, COMMENT_SECTION', max_length=40)),
                ('event_type', models.CharField(max_length=40)),
                ('interaction_strength', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('STRONG', 'Strong'), ('VERY_STRONG', 'Very Strong')], default='LOW', max_length=20)),
                ('interaction_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('session_id', models.CharField(blank=True, max_length=64, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_events_initiated', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_events_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['actor_user', 'target_user', 'created_at'], name='api_sociald_actor_u_f8c7d1_idx')],
            },
        ),
    ]
